# version format
version: 1.1.0.{build}

image: Visual Studio 2017

cache:
  - packages -> **\packages.config
  - c:\projects\pure\pure\node_modules -> **\packages.json
  
install:
  - set PATH=C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\MSBuild.exe;C:\Ruby25\bin;%PATH%
  #- cmd: gem install sassc
  - cmd: npm install -g grunt-cli
  - cmd: set UMBRACO_PACKAGE_MIN_VERSION=8.0.0
  - cmd: cd BuildPackage
  - cmd: Build.bat
  
branches:
  only: 
  - master

test: off
build: off

artifacts:
  - path: BuildPackage\artifacts\*.nupkg
  - path: BuildPackage\artifacts\*.zip
  
deploy:
  - provider: NuGet
    server:
    api_key:
      secure: 3rS8SSsTr0VHNAkG7ayAvic+yEedX8IIKq9QwaNrtLYDzgpyZJjY1mLuBYDZF0Qj
    skip_symbols: false      
    symbol_server:    
    artifact: /.*\.nupkg/
    on:
        branch: master
        appveyor_repo_tag: true      
    
  - provider: GitHub
    tag: v1.1.0
    release: Release 1.1.0
    description: "Semvar be damned, call this v1.1.0 - adds button to editor to toggle Pure editing"
    force_update: true
    auth_token:
        secure: Otbl8p8qCwciDqJgSWCyN0Arfs5XS1CwiHcK+r0F6uz9Rxt4gzBFvlc3cjPV3NxR
    artifact: /.*\.zip/     
    on:
        branch: master
        appveyor_repo_tag: true    
